<x-layouts.app title="Dashboard Admin - Koperasi Sipaduhok">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div><p class="font-extrabold uppercase tracking-widest text-primary">Admin Seller</p><h1 class="mt-1 text-3xl font-black text-slate-900">Dashboard Koperasi</h1><p class="mt-1 text-slate-500">Kelola toko, pembayaran, dan pengantaran dari satu panel.</p></div>
        <a href="{{ route('admin.products.create') }}" class="rounded-xl bg-primary px-5 py-3 text-center font-black text-white transition hover:bg-secondary">+ Tambah Produk</a>
    </div>
    <a href="{{ route('admin.settings.payment.edit') }}" class="mt-6 flex flex-col gap-3 rounded-2xl border p-4 transition hover:shadow-md sm:flex-row sm:items-center sm:justify-between {{ $paymentStatus['ready'] ? 'border-emerald-200 bg-emerald-50' : 'border-amber-200 bg-amber-50' }}">
        <span class="flex items-start gap-3"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-xl {{ $paymentStatus['ready'] ? 'bg-emerald-600' : 'bg-amber-500' }} text-white"><i class="fas fa-credit-card" aria-hidden="true"></i></span><span><strong class="block text-slate-900">{{ $paymentStatus['ready'] ? 'Midtrans siap menerima pembayaran' : 'Konfigurasi pembayaran perlu diperiksa' }}</strong><span class="mt-1 block text-xs leading-5 text-slate-600">{{ $paymentStatus['ready'] ? 'Environment '.ucfirst($paymentStatus['environment']).' · callback dan Snap siap digunakan.' : 'Lengkapi Server Key, Client Key, environment, dan aktivasi Midtrans sebelum toko production.' }}</span></span></span>
        <span class="shrink-0 text-sm font-extrabold text-primary">Buka pengaturan <i class="fas fa-arrow-right ml-1" aria-hidden="true"></i></span>
    </a>
    <div class="mt-6 grid grid-cols-2 gap-3 xl:grid-cols-4">
        <a href="{{ route('admin.products.index') }}" class="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-primary"><p class="text-sm text-slate-500">Produk</p><p class="mt-2 text-3xl font-black">{{ $productCount }}</p><p class="mt-2 text-xs font-bold text-primary">Kelola katalog →</p></a>
        <a href="{{ route('admin.products.index') }}" class="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-red-300"><p class="text-sm text-slate-500">Stok ≤ 5</p><p class="mt-2 text-3xl font-black text-red-600">{{ $lowStockCount }}</p><p class="mt-2 text-xs text-slate-400">Perlu diperiksa</p></a>
        <a href="{{ route('admin.orders.index', ['status' => 'pending_payment']) }}" class="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-primary"><p class="text-sm text-slate-500">Menunggu Bayar</p><p class="mt-2 text-3xl font-black text-primary">{{ $pendingPaymentCount }}</p><p class="mt-2 text-xs text-slate-400">Cek status pembayaran</p></a>
        <a href="{{ route('admin.orders.index', ['status' => 'processing']) }}" class="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-primary"><p class="text-sm text-slate-500">Pesanan Masuk</p><p class="mt-2 text-3xl font-black text-primary">{{ $incomingOrderCount }}</p><p class="mt-2 text-xs text-slate-400">Menunggu tindakan</p></a>
        <a href="{{ route('admin.orders.index', ['status' => 'out_for_delivery']) }}" class="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-secondary"><p class="text-sm text-slate-500">Antrean Pengiriman</p><p class="mt-2 text-3xl font-black text-secondary">{{ $deliveryCount }}</p><p class="mt-2 text-xs text-slate-400">Kurir toko & bukti tiba</p></a>
        <a href="{{ route('admin.buyers.index') }}" class="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-primary"><p class="text-sm text-slate-500">Akun Pembeli</p><p class="mt-2 text-3xl font-black">{{ $buyerCount }}</p><p class="mt-2 text-xs text-slate-400">Satu role pembeli</p></a>
        <a href="{{ route('admin.reports.sales') }}" class="col-span-2 rounded-2xl bg-gradient-to-r from-primary to-secondary p-5 text-white transition hover:shadow-lg"><p class="text-sm text-blue-50">Total Penjualan Selesai</p><p class="mt-2 text-2xl font-black text-accent-yellow">Rp {{ number_format($completedRevenue, 0, ',', '.') }}</p><p class="mt-2 text-xs font-bold text-white">Buka laporan penjualan →</p></a>
    </div>
    <section class="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white">
        <div class="flex items-center justify-between border-b border-slate-200 p-5"><div><h2 class="font-black">Pesanan Terbaru</h2><p class="text-xs text-slate-500">Aktivitas transaksi koperasi terkini</p></div><a href="{{ route('admin.orders.index') }}" class="text-sm font-bold text-primary hover:text-secondary">Semua pesanan</a></div>
        <div class="divide-y divide-slate-100">@forelse($recentOrders as $order)<a href="{{ route('admin.orders.show', $order) }}" class="flex flex-col gap-2 p-4 hover:bg-slate-50 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-mono text-sm font-bold">{{ $order->invoice_number }}</p><p class="text-sm text-slate-500">{{ $order->student_name }} · {{ $order->class_name }}</p></div><div class="sm:text-right"><p class="text-sm font-bold">{{ $order->statusLabel() }}</p><p class="text-sm">Rp {{ number_format($order->total, 0, ',', '.') }}</p></div></a>@empty<p class="p-8 text-center text-slate-500">Belum ada pesanan.</p>@endforelse</div>
    </section>
</x-layouts.app>
