<x-layouts.app title="Dashboard Admin - Koperasi Sipaduhok">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="font-bold uppercase tracking-wide text-orange-600">Admin Seller</p><h1 class="text-3xl font-black text-slate-900">Dashboard Koperasi</h1></div><a href="{{ route('admin.products.create') }}" class="rounded-xl bg-orange-500 px-4 py-3 text-center font-bold text-slate-950">Tambah Produk</a></div>
    <div class="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-4">
        <div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Produk</p><p class="mt-2 text-3xl font-black">{{ $productCount }}</p></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Stok ≤ 5</p><p class="mt-2 text-3xl font-black text-red-600">{{ $lowStockCount }}</p></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Pesanan Masuk</p><p class="mt-2 text-3xl font-black text-orange-600">{{ $incomingOrderCount }}</p></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Penjualan Selesai</p><p class="mt-2 text-xl font-black">Rp {{ number_format($completedRevenue, 0, ',', '.') }}</p></div>
    </div>
    <section class="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="flex items-center justify-between border-b border-slate-200 p-5"><h2 class="font-black">Pesanan Terbaru</h2><a href="{{ route('admin.orders.index') }}" class="text-sm font-bold text-orange-600">Semua pesanan</a></div><div class="divide-y divide-slate-100">@forelse($recentOrders as $order)<a href="{{ route('admin.orders.show', $order) }}" class="flex flex-col gap-2 p-4 hover:bg-slate-50 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-mono text-sm font-bold">{{ $order->invoice_number }}</p><p class="text-sm text-slate-500">{{ $order->student_name }} · {{ $order->class_name }}</p></div><div class="sm:text-right"><p class="text-sm font-bold">{{ $order->statusLabel() }}</p><p class="text-sm">Rp {{ number_format($order->total, 0, ',', '.') }}</p></div></a>@empty<p class="p-6 text-center text-slate-500">Belum ada pesanan.</p>@endforelse</div></section>
</x-layouts.app>
