<x-layouts.app title="Laporan Penjualan">
    <div><p class="text-sm font-extrabold uppercase tracking-widest text-primary">Rekap Toko</p><h1 class="mt-1 text-3xl font-black text-slate-900">Laporan Penjualan</h1><p class="mt-1 text-slate-500">Hanya menghitung pesanan yang sudah dikonfirmasi selesai oleh pembeli.</p></div>
    <form method="GET" class="mt-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_1fr_auto]"><label class="text-sm font-bold">Dari tanggal<input name="start_date" type="date" value="{{ request('start_date', $start->toDateString()) }}" class="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3"></label><label class="text-sm font-bold">Sampai tanggal<input name="end_date" type="date" value="{{ request('end_date', $end->toDateString()) }}" class="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3"></label><button class="self-end rounded-xl bg-primary px-5 py-3 font-bold text-white hover:bg-secondary">Tampilkan</button></form>
    <div class="mt-5 grid grid-cols-2 gap-3 xl:grid-cols-4"><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Omzet selesai</p><p class="mt-2 text-xl font-black text-slate-900">Rp {{ number_format($revenue, 0, ',', '.') }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Pesanan selesai</p><p class="mt-2 text-3xl font-black text-primary">{{ $orderCount }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Produk terjual</p><p class="mt-2 text-3xl font-black text-secondary">{{ $itemsSold }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Biaya kurir</p><p class="mt-2 text-xl font-black text-slate-900">Rp {{ number_format($shippingRevenue, 0, ',', '.') }}</p></div></div>
    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
        <section class="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><div class="border-b border-slate-200 p-5"><h2 class="font-black">Pesanan Selesai</h2></div><table class="min-w-full text-sm"><thead class="bg-blue-50/70 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Invoice</th><th class="p-4">Pembeli</th><th class="p-4">Selesai</th><th class="p-4 text-right">Total</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($orders as $order)<tr><td class="p-4"><a href="{{ route('admin.orders.show', $order) }}" class="font-mono font-bold text-primary">{{ $order->invoice_number }}</a></td><td class="p-4">{{ $order->buyer_name }}</td><td class="p-4">{{ $order->completed_at?->format('d/m/Y H:i') }}</td><td class="p-4 text-right font-black">Rp {{ number_format($order->total, 0, ',', '.') }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-slate-500">Belum ada penjualan selesai pada periode ini.</td></tr>@endforelse</tbody></table><div class="p-4">{{ $orders->links() }}</div></section>
        <section class="h-fit rounded-2xl bg-gradient-to-br from-primary to-secondary p-5 text-white"><h2 class="font-black">Produk Terlaris</h2><div class="mt-4 divide-y divide-white/15">@forelse($topProducts as $product)<div class="py-3"><div class="flex justify-between gap-3 text-sm"><span class="font-bold">{{ $product->product_name }}</span><span class="text-accent-yellow">{{ $product->total_quantity }} item</span></div><p class="mt-1 text-xs text-blue-50">Rp {{ number_format($product->total_sales, 0, ',', '.') }}</p></div>@empty<p class="py-5 text-sm text-blue-50">Belum ada data.</p>@endforelse</div></section>
    </div>
</x-layouts.app>
