<x-layouts.app title="Pesanan Masuk">
    <h1 class="text-3xl font-black">Pesanan Masuk</h1>
    <form method="GET" class="mt-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-[1fr_220px_auto]">
        <input name="search" value="{{ request('search') }}" placeholder="Invoice atau nama siswa" class="rounded-xl border border-slate-300 px-4 py-3">
        <select name="status" class="rounded-xl border border-slate-300 px-4 py-3"><option value="">Semua status</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>@endforeach</select>
        <button class="rounded-xl bg-primary px-5 py-3 font-bold text-white hover:bg-secondary">Filter</button>
    </form>
    <div class="mt-5 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table class="min-w-full text-sm"><thead class="bg-blue-50/70 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Invoice</th><th class="p-4">Siswa</th><th class="p-4">Status</th><th class="p-4">Pembayaran</th><th class="p-4 text-right">Total</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($orders as $order)<tr class="hover:bg-blue-50/40"><td class="p-4"><a href="{{ route('admin.orders.show', $order) }}" class="font-mono font-bold text-primary">{{ $order->invoice_number }}</a><p class="text-xs text-slate-500">{{ $order->created_at->format('d/m/Y H:i') }}</p></td><td class="p-4"><p class="font-bold">{{ $order->student_name }}</p><p class="text-xs text-slate-500">{{ $order->class_name }}</p></td><td class="p-4 font-bold">{{ $order->statusLabel() }}</td><td class="p-4"><p class="font-semibold">{{ $order->payment_status->label() }}</p><p class="text-xs text-slate-500">{{ ucfirst($order->payment_gateway) }}</p></td><td class="p-4 text-right font-black">Rp {{ number_format($order->total, 0, ',', '.') }}</td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-slate-500">Belum ada pesanan.</td></tr>@endforelse</tbody></table></div>
    <div class="mt-6">{{ $orders->links() }}</div>
</x-layouts.app>
