<x-layouts.app title="Pesanan {{ $order->invoice_number }}">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p class="font-bold uppercase tracking-wide text-orange-600">Kelola Pesanan</p><h1 class="font-mono text-2xl font-black">{{ $order->invoice_number }}</h1><p class="text-slate-500">{{ $order->student_name }} · {{ $order->class_name }}</p></div><div class="flex gap-2"><a href="{{ route('admin.orders.invoice', $order) }}" class="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-bold">Invoice</a><span class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white">{{ $order->statusLabel() }}</span></div></div>
    <div class="mt-6 grid gap-6 lg:grid-cols-[1fr_360px]">
        <div class="space-y-6">
            <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-black">Item</h2><div class="mt-4 divide-y divide-slate-100">@foreach($order->items as $item)<div class="flex justify-between gap-3 py-3 text-sm"><span>{{ $item->product_name }} × {{ $item->quantity }}</span><span class="font-bold">Rp {{ number_format($item->subtotal, 0, ',', '.') }}</span></div>@endforeach</div><div class="mt-4 flex justify-between border-t border-slate-200 pt-4 text-lg font-black"><span>Total + Kurir</span><span>Rp {{ number_format($order->total, 0, ',', '.') }}</span></div></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-black">Penerima & Alamat</h2><div class="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><p class="text-slate-500">Pembeli</p><p class="font-bold">{{ $order->buyer_name }}</p><p>{{ $order->phone }}</p></div><div><p class="text-slate-500">Siswa</p><p class="font-bold">{{ $order->student_name }}</p><p>{{ $order->class_name }}</p></div><div class="sm:col-span-2"><p class="text-slate-500">Alamat pengantaran</p><p class="mt-1 whitespace-pre-line">{{ $order->delivery_address }}</p></div></div></section>
            @if($order->delivery_proof_path)<section class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><h2 class="font-black text-emerald-900">Bukti Paket Tiba</h2><img src="{{ Storage::disk('public')->url($order->delivery_proof_path) }}" alt="Bukti paket tiba" class="mt-4 max-h-96 w-full rounded-xl bg-white object-contain">@if($order->delivery_note)<p class="mt-3 text-sm text-emerald-800">{{ $order->delivery_note }}</p>@endif</section>@endif
            <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-black">Histori Internal</h2><ol class="mt-4 space-y-3">@foreach($order->histories as $history)<li class="border-l-2 border-orange-400 pl-4 text-sm"><p class="font-bold">{{ str($history->to_status)->replace('_', ' ')->title() }}</p><p class="text-slate-500">{{ $history->created_at->format('d/m/Y H:i') }} · {{ $history->actor?->name ?? 'Sistem' }}</p>@if($history->note)<p class="mt-1">{{ $history->note }}</p>@endif</li>@endforeach</ol></section>
        </div>
        <aside class="h-fit rounded-2xl bg-slate-900 p-6 text-white">
            <h2 class="text-lg font-black">Aksi Pesanan</h2>
            <p class="mt-1 text-sm text-slate-400">Tiap perubahan disimpan ke histori internal.</p>
            @if($order->status === App\Enums\OrderStatus::PendingPayment)
                <div class="mt-5 rounded-xl bg-slate-800 p-4 text-sm"><p>Status pembayaran: <strong>{{ strtoupper($order->payment_status->value) }}</strong></p><p class="mt-1 break-all text-xs text-slate-400">{{ $order->payment_reference }}</p></div>
                <form method="POST" action="{{ route('admin.orders.confirm-payment', $order) }}" class="mt-4" onsubmit="return confirm('Konfirmasi pembayaran dan kurangi stok?')">@csrf<button class="w-full rounded-xl bg-orange-500 px-4 py-3 font-bold text-slate-950">Konfirmasi Pembayaran</button></form>
            @elseif($order->status === App\Enums\OrderStatus::Processing)
                <form method="POST" action="{{ route('admin.orders.update-status', $order) }}" class="mt-5 space-y-3">@csrf @method('PATCH')<input type="hidden" name="status" value="ready"><textarea name="note" rows="2" placeholder="Catatan opsional" class="w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-sm text-white"></textarea><button class="w-full rounded-xl bg-orange-500 px-4 py-3 font-bold text-slate-950">Tandai Siap Dikirim</button></form>
            @elseif($order->status === App\Enums\OrderStatus::Ready)
                <form method="POST" action="{{ route('admin.orders.update-status', $order) }}" class="mt-5 space-y-3">@csrf @method('PATCH')<input type="hidden" name="status" value="out_for_delivery"><textarea name="note" rows="2" placeholder="Catatan kurir opsional" class="w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-sm text-white"></textarea><button class="w-full rounded-xl bg-orange-500 px-4 py-3 font-bold text-slate-950">Kurir Mulai Mengantar</button></form>
            @elseif($order->status === App\Enums\OrderStatus::OutForDelivery)
                <form method="POST" action="{{ route('admin.orders.mark-delivered', $order) }}" enctype="multipart/form-data" class="mt-5 space-y-3">@csrf<label class="block text-sm font-bold">Foto bukti paket tiba<input type="file" name="delivery_proof" accept="image/*" required class="mt-2 block w-full rounded-xl border border-slate-700 bg-slate-800 p-2 text-xs"></label><textarea name="delivery_note" rows="3" placeholder="Catatan penyerahan (opsional)" class="w-full rounded-xl border border-slate-700 bg-slate-800 px-4 py-3 text-sm text-white"></textarea><button class="w-full rounded-xl bg-orange-500 px-4 py-3 font-bold text-slate-950">Unggah Bukti Tiba</button></form>
            @elseif($order->status === App\Enums\OrderStatus::Delivered)
                <div class="mt-5 rounded-xl bg-emerald-900/50 p-4 text-sm text-emerald-100">Bukti tiba sudah diunggah. Menunggu pembeli menekan konfirmasi barang diterima.</div>
            @elseif($order->status === App\Enums\OrderStatus::Completed)
                <div class="mt-5 rounded-xl bg-emerald-900/50 p-4 text-sm text-emerald-100">Pesanan telah dikonfirmasi selesai.</div>
            @endif
        </aside>
    </div>
</x-layouts.app>
